apiVersion: v1
kind: ConfigMap
metadata:
  name: service-directory-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: service-directory
data:
  services.json: |
    {{- toJson .Values.services | nindent 4 }} 