apiVersion: v1
kind: Service
metadata:
  name: service-directory
  namespace: {{ .Release.Namespace }}
  labels:
    app: service-directory
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port | default 80 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: service-directory 