replicaCount: 1

image:
  repository: service-directory
  tag: latest
  pullPolicy: Always

environment: production

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    metadata.service-catalog/omit: "true"
  hosts:
    - host: service-directory.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
    config:
      - secretName: service-directory-tls
        hosts:
          - service-directory.example.com

services:
  - name: "Service Directory"
    description: "Internal service directory and catalog"
    url: "https://service-directory.example.com"
    icon: "search"
    category: "Tools"
